# Generated by Django 4.2.6 on 2023-10-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderappp', '0003_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
